name: 'data_models'
version: '1.0.0'
config-version: 2

profile: 'data_models'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  data_models:
    staging:
      +materialized: view
      +schema: staging # creates public_staging schema
    marts:
      +materialized: table
      +schema: analytics # creates public_analytics schema
